name: keep alive

on:
  schedule:
  - cron:  '*/9 * * * *'

jobs:
  keepalive:
    runs-on: ubuntu-latest

    steps:
    - name: ping the application
      run: curl https://${{ secrets.HEROKU_APPNAME }}.herokuapp.com/ping